In [2]:
import pandas as pd

In [3]:
cus=pd.read_excel("../dataset/Ecomm.xlsx",sheet_name='CustomerDetail')

In [4]:
ord=pd.read_excel("../dataset/Ecomm.xlsx",sheet_name='Jan')

In [5]:
cus.shape

(24, 12)

In [6]:
cus.head(2)

,CustomerID,CustomerID.1,Order Date,Month,MonthName,DateInText,Customer Name,State or Province,City,Gender,Gender.1,Gender.2
0,CUS7253,7253,2015-01-07,1,Jan,01/07/2015,Bonnie Potter,Washington,Anacortes,M,1,MALE
1,CUS4875,4875,2015-06-13,6,Jun,06/13/2015,Ronnie Proctor,California,San Gabriel,F,0,FEMALE

In [7]:
cus=cus.drop(columns=['CustomerID','Month','DateInText','Gender.1','Gender','MonthName'])

In [8]:
cus.head(2)

,CustomerID.1,Order Date,Customer Name,State or Province,City,Gender.2
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [9]:
cus=cus.rename(columns={'CustomerID.1':'CustomerID','Gender.2':'Gender'})

In [10]:
cus.head(2)

,CustomerID,Order Date,Customer Name,State or Province,City,Gender
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [11]:
cus.isnull().sum().sum()

0

In [12]:
ord.shape

(1952, 8)

In [13]:
ord.head(2)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [14]:
ord.isnull().sum().sum()

0

In [15]:
ord=ord.rename(columns={'Quantity ordered new':'Qty'})

In [16]:
ord.head(2)

,Order ID,CustomerID,Amount,Profit,Qty,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [17]:
cus['Order Date']=pd.to_datetime(cus['Order Date'])

In [18]:
cus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         24 non-null     int64
 1   Order Date         24 non-null     datetime64[ns]
 2   Customer Name      24 non-null     object
 3   State or Province  24 non-null     object
 4   City               24 non-null     object
 5   Gender             24 non-null     object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.3+ KB

In [19]:
len(cus.CustomerID.unique())

24

In [20]:
ord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              1952 non-null   int64
 1   CustomerID            1952 non-null   int64
 2   Amount                1952 non-null   float64
 3   Profit                1952 non-null   float64
 4   Qty                   1952 non-null   int64
 5   Product Category      1952 non-null   object
 6   Product Sub-Category  1952 non-null   object
 7   Payment Mode          1952 non-null   object
dtypes: float64(2), int64(3), object(3)
memory usage: 122.1+ KB

In [21]:
len(ord['Order ID'].unique())

1365

In [22]:
ord.shape

(1952, 8)

In [23]:
ord['Order ID'].value_counts()

Order ID
86960    5
87033    5
88060    5
47108    4
88219    4
        ..
86827    1
90120    1
90121    1
89076    1
87530    1
Name: count, Length: 1365, dtype: int64

In [24]:
for i in range(0,cus.shape[0]):
    li=list(cus.loc[i])

In [25]:
li

[4568,
 Timestamp('2015-06-15 00:00:00'),
 'Ricky Hensley',
 'Oregon',
 'Gresham',
 'MALE']

In [26]:
ord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              1952 non-null   int64
 1   CustomerID            1952 non-null   int64
 2   Amount                1952 non-null   float64
 3   Profit                1952 non-null   float64
 4   Qty                   1952 non-null   int64
 5   Product Category      1952 non-null   object
 6   Product Sub-Category  1952 non-null   object
 7   Payment Mode          1952 non-null   object
dtypes: float64(2), int64(3), object(3)
memory usage: 122.1+ KB

In [27]:
import pandas as pd

In [28]:
cus=pd.read_csv("../dataset/customer.csv")
order=pd.read_csv("../dataset/orders.csv")

In [29]:
order.head(2)

,Order ID,CustomerID,Amount,Profit,Qty,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [30]:
df=pd.merge(order,cus,on='CustomerID',how='inner')

In [31]:
df.shape

(1952, 13)

In [32]:
ord['Payment Mode']

0       Credit Card
1       Credit Card
2       Credit Card
3       Credit Card
4       Credit Card
           ...
1947    Credit Card
1948    Credit Card
1949    Credit Card
1950    Credit Card
1951    Credit Card
Name: Payment Mode, Length: 1952, dtype: object

In [36]:
cus['Order Date'].unique()

array(['2015-01-07', '2015-06-13', '2015-02-15', '2015-05-12',
       '2015-04-08', '2015-05-28', '2015-02-12', '2015-05-15',
       '2015-05-21', '2015-01-28', '2015-05-02', '2015-02-22',
       '2015-03-27', '2015-01-20', '2015-03-12', '2015-06-15'],
      dtype=object)